### ISSUE TITLE
Remove hard-coded paths

### ISSUE THREAD

**Issue by tjpugh** [pughlab/iMATRIX-Atezo_Biomarker#1]
Notebook 01 begins with a series of hard-coded paths to "/Users/anabbi/OneDrive - UHN/Documents/". Need to replace these will relative paths that point to input files within the repository.

**Comment by tjpugh** [comment]
Actually, it looks like all of the notebooks are afflicted by this issue.

**Comment by anabbi** [comment]
Fixed. I am currently working on finalizing the Figure 4 and 5.
